metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "a0bd28475bdda6938a7a00521326da44426e3cb3558364b548cd829415899960"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "ZbGgBYxlED7e8k8bZ5wt+yfdkMDklLbrDR2uqg3wKVs="
metrics_token = "UP6PfeHDxBWxnp89oymHEPO5S99VtbVyOY2VQlFNrZA="