services:
  garage:
    container_name: garage
    image: docker.io/dxflrs/garage:v2.1.0
    restart: unless-stopped
    ports:
     - 3900:3900   ## s3 api
     - 3901:3901   ## rpc
     - 3902:3902   ## s3 web
    #- 3903:3903   ## admin api and '/metrics' for prometheus
    volumes:
      - ./config/garage.toml:/etc/garage.toml
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data

  filestash:
    image: docker.io/machines/filestash:latest
    container_name: filestash
    restart: unless-stopped
    volumes:
      - ./config/filestash.toml:/app/filestash.json
    ports:
      - "8334:8334"
    environment:
      - FS_LOG_LEVEL=info
      - S3_ENDPOINT=https://garages:3900
      - S3_REGION=garage
      - S3_ACCESS_KEY_ID=GK21225d83fe2e03c261de9c9a
      - S3_SECRET_ACCESS_KEY=a5d055c11a4ea2788891e297e4976a563361cc326beef8e58906fde9278c29ca
    depends_on:
      - garage